This is makeindex, version 2.15 [MiKTeX 2.9 64-bit] (kpathsea + Thai support).
Scanning style file C:/Users/Mntsos/Documents/Τα αρχεία μου/Projects/Thesis/ThesisTex/Thesis.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file Thesis.acn....done (9 entries accepted, 0 rejected).
Sorting entries....done (28 comparisons).
Generating output file Thesis.acr....done (26 lines written, 0 warnings).
Output written in Thesis.acr.
Transcript written in Thesis.alg.
